"""empty message

Revision ID: 503dfa449498
Revises: b620beef3fac
Create Date: 2020-07-25 08:37:10.895694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503dfa449498'
down_revision = 'b620beef3fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
